//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchFileRenamer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class FileRenamer : global::System.Configuration.ApplicationSettingsBase {
        
        private static FileRenamer defaultInstance = ((FileRenamer)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FileRenamer())));
        
        public static FileRenamer Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string workfolder {
            get {
                return ((string)(this["workfolder"]));
            }
            set {
                this["workfolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ignoreCase {
            get {
                return ((bool)(this["ignoreCase"]));
            }
            set {
                this["ignoreCase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool wannaReally {
            get {
                return ((bool)(this["wannaReally"]));
            }
            set {
                this["wannaReally"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mkv;mp3;mp4;avi;ogg;m4a")]
        public string extensionPreFilter {
            get {
                return ((string)(this["extensionPreFilter"]));
            }
            set {
                this["extensionPreFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int recursionLvl {
            get {
                return ((int)(this["recursionLvl"]));
            }
            set {
                this["recursionLvl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection simpleSearch {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["simpleSearch"]));
            }
            set {
                this["simpleSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection simpleReplace {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["simpleReplace"]));
            }
            set {
                this["simpleReplace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>(.+)</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection regexSearch {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["regexSearch"]));
            }
            set {
                this["regexSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>$1</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection regexReplace {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["regexReplace"]));
            }
            set {
                this["regexReplace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int lastUsedTab {
            get {
                return ((int)(this["lastUsedTab"]));
            }
            set {
                this["lastUsedTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableOutputFolder {
            get {
                return ((bool)(this["enableOutputFolder"]));
            }
            set {
                this["enableOutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string outputfolder {
            get {
                return ((string)(this["outputfolder"]));
            }
            set {
                this["outputfolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableExtensionPreFiltering {
            get {
                return ((bool)(this["enableExtensionPreFiltering"]));
            }
            set {
                this["enableExtensionPreFiltering"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoPreview {
            get {
                return ((bool)(this["autoPreview"]));
            }
            set {
                this["autoPreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hideSaveReset {
            get {
                return ((bool)(this["hideSaveReset"]));
            }
            set {
                this["hideSaveReset"] = value;
            }
        }
    }
}
